### ISSUE TITLE
Critical error : Could not load order - Order after payment

### ISSUE THREAD

**Issue by celi28** [btcpayserver/prestashop-plugin#50] opened 2022-05-03 05:48 UTC
**Describe the bug**
With order after payment option, I have a lot of critical errors.
Seems like a lot of orders failed to load after payment failure.

**To Reproduce**
1. Setup "Order after payment"
2. Fail to pay the invoice on time
3. Get redirected to redirect url

**Expected behavior**
Get redirected to main webpage / catch the error instead raising major failure.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version :  BTCPay Server v1.5.1.0 (Altcoins) 
- Deployment Method: Docker

**Logs (if applicable)**
![image](https://user-images.githubusercontent.com/16089668/166408929-00b50e82-b16c-45e1-9adf-04c6a93ba2b0.png)

**Comment by BitcoinMitchell** [comment] 2023-02-06 11:04
I am closing this issue for now since it has been over a year and I have been unable to reproduce. If it still happens with the current version of the plugin, please re-create the issue and prepare some way for me to test it.

**Closed as completed by BitcoinMitchell** 2023-02-06 11:04 UTC
Labels: awaiting response, cannot reproduce
